In [1]:
import pandas as pd
import numpy as np

In [ ]:
# df = pd.read_json('../artifacts/sample_data/6411_sample.json')
# df = pd.read_json('/scratch/ayl316/ttml_mr_data/xml_jsons/6411.json', lines = True)

In [ ]:
# df_sample

In [ ]:
# df.columns

In [34]:
aoc_df = pd.read_stata('/scratch/ns4486/motivated-reasoning/data/aoc_district/districtAOC_dupldropped.dta')
# aoc_df = pd.read_csv('../artifacts/sample_data/aoc_district_sample.csv')

TypeError: read_stata() got an unexpected keyword argument 'encoding'

In [35]:
pd.set_option('display.max_columns', None)

In [36]:
aoc_df.head()

,CIRCUIT,FILEDATE,JURIS,NOS,ORIGIN,RESIDENC,CLASSACT,DEMANDED,TERMDATE,DISP,PROCPROG,NOJ,AMTREC,JUDGMENT,MAGISINV,OTHERINV,TAPEYEAR,docketnumber,district,office,termjudg,filejudg,filemag,county,casename,fdateuse,termmag,tdateuse,TRANSDAT,TRCLACT,DJOINED,PRETRIAL,TRIBEGAN,TRIALEND,PROSE,titl,section,subsect,arbit,mdldock,plt,def,transoff,transdoc,transorg,trmarb,ifp,statuscd
0,0.0,-1606.0,5.0,370.0,1.0,-8.0,-9.0,0.0,1970-05-26,7.0,2.0,0.0,0.0,-9.0,-9.0,-9.0,1970.0,0553529,90,1,,,,-9,CURTIS V FOOTE CONE BELDING COR,9912.0,,9912.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,,,,,,,,
1,0.0,95.0,5.0,350.0,4.0,-8.0,-9.0,0.0,1970-04-10,5.0,4.0,0.0,0.0,-9.0,-9.0,-9.0,1970.0,0591077,90,1,,,,-9,WADE V PREMIER CAB ASSN ET AL,9912.0,,9912.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,,,,,,,,
2,0.0,413.0,5.0,290.0,4.0,-8.0,-9.0,0.0,1970-02-13,1.0,1.0,4.0,0.0,-9.0,-9.0,-9.0,1970.0,0591366,90,1,,,,-9,BROWN V DIGGS ET AL,9912.0,,9912.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,,,,,,,,
3,0.0,2534.0,5.0,360.0,4.0,-8.0,-9.0,0.0,1969-10-27,7.0,9.0,0.0,0.0,-9.0,-9.0,-9.0,1970.0,6003837,90,1,,,,-9,HUHN V CONTINENTAL BAKING CO,9912.0,,9912.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,,,,,,,,
4,0.0,1510.0,2.0,290.0,4.0,-8.0,-9.0,0.0,1969-10-08,7.0,5.0,0.0,0.0,-9.0,-9.0,-9.0,1970.0,6004181,90,1,,,,-9,OELSCHLAEGER V UDALL SECY,9912.0,,9912.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,,,,,,,,

In [42]:
for col in aoc_df.columns:
    if aoc_df[col].value_counts().shape[0] == 1:
        print(col, aoc_df[col].unique())

termjudg ['']
filejudg ['']
filemag ['']
termmag ['']

In [7]:
for col in aoc_df.columns:
    print(col)

CIRCUIT
FILEDATE
JURIS
NOS
ORIGIN
RESIDENC
CLASSACT
DEMANDED
TERMDATE
DISP
PROCPROG
NOJ
AMTREC
JUDGMENT
MAGISINV
OTHERINV
TAPEYEAR
docketnumber
district
office
termjudg
filejudg
filemag
county
casename
fdateuse
termmag
tdateuse
TRANSDAT
TRCLACT
DJOINED
PRETRIAL
TRIBEGAN
TRIALEND
PROSE
titl
section
subsect
arbit
mdldock
plt
def
transoff
transdoc
transorg
trmarb
ifp
statuscd

In [31]:
aoc_df['filejudg'].unique()

array([''], dtype=object)

In [32]:
aoc_df['termjudg'].unique()

array([''], dtype=object)

In [8]:
judge_df = pd.read_stata('/scratch/ayl316/ttml_mr_data/judges/JudgesBioReshaped_TOUSE.dta')

In [9]:
judge_df.shape

(4096, 187)

In [10]:
for col in judge_df.columns:
    print(col)

songername
judgeidentificationnumber
Term
id
AppointmentDate
TerminationDate
courtname
courttype
abarating
AbaUpdate
SenateConfirmationdate
RecessAppointDate
birthday
birthmonth
birthyear
deathmonth
deathday
deathyear
JudgeAssignedCourt
judgelastname
judgefirstname
judgemiddlename
suffix
Circuitjudge
SeatState
retirementfromactiveservice
dateaschiefjudgebegin
presidentname
seconddateaschiefjudgebegin
senatevoicevote
senatevoteayesnays
Committeeactiondate
Degree1
Degree2
Degree3
Degree4
Degree5
degreeyear1
degreeyear2
degreeyear3
degreeyear4
degreeyear5
Committeeaction
ageon
vicelastnamepredecessor
vicefirstnamepredecessor
hearings
reportnumber
authorizationlegislation
placeofbirthcity
placeofbirthstate
placeofdeathcity
placeofdeathstate
deathdate
party_Updated
dateaschiefjudgeend
seconddateaschiefjudgeend
renominatingpresidentname
partyaffiliationofrenompres
referraldatejudicialcom
degree
degree_law
degree_other
district
nominationdatesenateexecutivej
genderNew
raceorethnicity
partyaffiliationofpresident
recessappointmentdate
committeeaction
committeeactiondate
senatevotedateconfirmationdate
commissiondate
dateoftermination
terminationspecificreason
nameofschool1
degree1
nameofschool2
degree2
nameofschool3
degree3
nameofschool4
degree4
nameofschool5
degree5
employmenttextfield
bankruptcyandmagistrateservice
Nominationdate
District_Circuit
party
pres
left
state
city
appres
aba
congresi
unityi
hdem
hrep
sdem
srep
hother
sother
x_dem
x_republican
x_instate_ba
x_elev
x_unity
x_aba
x_crossa
x_pfedjdge
x_pindreg1
x_plawprof
x_pscab
x_pcab
x_pusa
x_pssenate
x_paag
x_psp
x_pslc
x_pssc
x_pshouse
x_psg
x_psgo
x_psenate
x_psatty
x_pprivate
x_pmayor
x_plocct
x_phouse
x_pgov
x_pda
x_pcc
x_pccoun
x_pausa
x_pasatty
x_pag
x_pada
x_pgovt
x_llm_sjd
x_protestant
x_evangelical
x_mainline
x_noreligion
x_catholic
x_jewish
x_black
x_nonwhite
x_female
x_jd_public
x_ba_public
x_b10s
x_b20s
x_b30s
x_b40s
x_b50s
x_pbank
x_pmag
SchoolState1
Public1
Private1
SchoolState2
Public2
Private2
SchoolState3
Public3
Private3
SchoolState4
Public4
Private4
SchoolState5
Public5
Private5
TonotInclude
idtocorrrect
ayear
x_ageon40s
x_ageon50s
x_ageon60s
x_ageon40orless
x_ageon70ormore
pres_correct2
political_party
_merge
x_pago
startdate

In [30]:
judge_df['id'].value_counts().shape

(3224,)

In [43]:
judge_df['songername'].head()

0               ABRAMS, RONNIE
1          ABRUZZO, MATTHEW J.
2           ACHESON, MARCUS W.
3           ACHESON, MARCUS W.
4    ACKER, WILLIAM MARSH, JR.
Name: songername, dtype: object